name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Maven Central credentials
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          # Configure the server credentials for the Maven Central (Sonatype) serverId used in pom.xml
          server-id: 'central'
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          # Import GPG key to sign artifacts (required by Central)
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Build and deploy to OSSRH (Central staging)
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: mvn -B -ntp -Prelease clean verify -DskipTests

# Notes:
# - Ensure the following repository secrets are set:
#   - MAVEN_CENTRAL_USERNAME: Your Sonatype (Maven Central) username
#   - MAVEN_CENTRAL_PASSWORD: Your Sonatype (Maven Central) password or token
#   - MAVEN_GPG_PRIVATE_KEY: ASCII-armored GPG private key used for signing (full exported key content)
#   - MAVEN_GPG_PASSPHRASE: Passphrase for the GPG private key
# - The pom.xml uses the 'central' serverId in the central-publishing plugin within the 'release' profile.
# - This workflow triggers when a GitHub Release is published or when manually dispatched.
